export default {
  mutations: {
    GETUSER: "GETUSER",
    NUEVOUSUARIO: "NUEVOUSUARIO",
    DESTROYSESSION: "DESTROYSESSION",
    STORESESION: "STORESESION",
    ROLES: "ROLES",
    SETMENSAJESUCCESS: "SETMENSAJESUCCESS"
  },
  getters: {
    USER: "USER",
    LOGGED: "LOGGED",
    ERROR: "ERROR",
    ROLE: "ROLE",
    MENSAJESUCCESS: "MENSAJESUCCESS"
  },
  actions: {
    LOGIN: "LOGIN",
    REGISTRO: "REGISTRO",
    LOGOUT: "LOGOUT",
    REFRESHTOKEN: "REFRESHTOKEN",
    REFRESHPASS: "REFRESHPASS"
  }
};
