export default {
  mutations: {
    SETQR: "SETQR",
    SETHISTORIAL: "SETHISTORIAL",
    SETARANCELES: "SETARANCELES",
    SETHOME: "SETHOME",
    SETPERFIL: "SETPERFIL",
    SETERRORS: "SETERRORS"
  },
  getters: {
    GETQR: "GETQR",
    GETHISTORIAL: "GETHISTORIAL",
    GETARANCELES: "GETARANCELES",
    GETHOME: "GETHOME",
    GETPERFIL: "GETPERFIL",
    GETERRORS: "GETERRORS"
  },
  actions: {
    QR:"QR",
    HISTORIAL:"HISTORIAL",
    ARANCELES: "ARANCELES",
    HOME: "HOME",
    PERFIL: "PERFIL"
  }
};
