export default {
  mutations: {
    SETQR: "SETQR",
    SETHISTORIAL: "SETHISTORIAL",
    SETARANCELES: "SETARANCELES",
    SETHOME: "SETHOME",
    SETPERFIL: "SETPERFIL",
    SETERRORS: "SETERRORS",
    VERIFICAEXISTEUSUARIO: "VERIFICAEXISTEUSUARIO",
    DESTROYDATA: "DESTROYDATA",
    SETUSUARIOS: "SETUSUARIOS"
  },
  getters: {
    GETQR: "GETQR",
    GETHISTORIAL: "GETHISTORIAL",
    GETARANCELES: "GETARANCELES",
    GETHOME: "GETHOME",
    GETPERFIL: "GETPERFIL",
    GETERRORS: "GETERRORS",
    GETUSUARIOS: "GETUSUARIOS"
  },
  actions: {
    QR: "QR",
    HISTORIAL: "HISTORIAL",
    ARANCELES: "ARANCELES",
    HOME: "HOME",
    PERFIL: "PERFIL",
    DESTROYDATA: "DESTROYDATA",
    USUARIOS: "USUARIOS"
  }
};
